/// <reference types="next" />
/// <reference types="next/image-types/global" />
/// <reference path="./.next/types/routes.d.ts" />

// This file is automatically generated by Next.js.
// Do not edit it manually.
